const data = [
  {
    name: "Nike cap",
    slug: "nike-cap",
    category: "cap",
    image: "./images/p1.jpeg",
    price: 30,
    stock: 30,
    brand: "Nike",
    rating: 4.3,
    reviewNum: 13,
    description: "a beadutiful cap for summer",
  },
  {
    name: "Adidas shirt",
    slug: "adidas-shirt",
    category: "shirt",
    image: "./images/p2.webp",
    price: 60,
    stock: 90,
    brand: "Adidas",
    rating: 4.8,
    reviewNum: 33,
    description: "always adidas classical shirt",
  },
  {
    name: "Lee classical jeans",
    slug: "lee-classical-jeans",
    category: "pants",
    image: "./images/p3.webp",
    price: 90,
    stock: 39,
    brand: "Lee",
    rating: 4.9,
    reviewNum: 76,
    description: "The only one you need",
  },
  {
    name: "Selected jacket",
    slug: "selected-jacket",
    category: "jacket",
    image: "./images/p4.jpg",
    price: 300,
    stock: 20,
    brand: "Selected",
    rating: 4.6,
    reviewNum: 20,
    description: "Choice of the men",
  },
];

export { data };
